name: Greetings

on: [pull_request, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: 'Hey! Thanks for pointing out a problem. I will look into it as soon as possible.'' first issue'
        pr-message: 'Thank you for your suggested changes. I will look at it as soon as possible.'' first pr'
